from Conexio import Conexio
mydb = Conexio()
mycursor = mydb.cursor()

nMonth = 12
nameList = "decemberList";

query = "SELECT character_id, name, anime_id, anime_image, character_image, character_thumb, gender, origin, description_type,day, month FROM personatges WHERE month ={0}".format(nMonth) 
mycursor.execute(query)
myresult = mycursor.fetchall()

f = open("test.js", "a")
f.write("\n //Autogenerated "+nameList)
f.write("\nvar "+nameList+" = [")
for x in myresult:
    structure = {"character_id": x[0], "name": x[1], "anime_id": x[2], "anime_image": x[3], "character_image": x[4],
"character_thumb": x[5], "gender": x[6],  "origin": x[7], "description_type": x[8], "day": x[9], "month": x[10]}
    f.write(str(structure)+",\n")
f.write("];\n\n")

f.close()
print("hecho "+str(nMonth)+" "+str(nameList))