from Conexio import Conexio

def generaMonthList(nameFile, nameList, nMonth):
    try:
        mydb = Conexio()
        mycursor = mydb.cursor()
        #query = "SELECT character_id, name, anime_id, anime_image, character_image, character_thumb, gender, origin, description_type,day, month FROM personatges WHERE month ={0}".format( nMonth)
        query = "SELECT character_id, name, anime_id, anime_image, character_image, character_thumb, gender, origin, description_type,day, month FROM personatges"
        mycursor.execute(query)
        myresult = mycursor.fetchall()

        f = open(nameFile, "a")
        f.write("\n //Autogenerated "+nameList)
        f.write("\nvar "+nameList+" = [")
        for x in myresult:
            structure = {"character_id": x[0], "name": x[1], "anime_id": x[2], "anime_image": x[3], "character_image": x[4],
                        "character_thumb": x[5], "gender": x[6],  "origin": x[7], "description_type": x[8], "day": x[9], "month": x[10]}
            f.write(str(structure)+",\n")
        f.write("];\n\n")

        f.close()
        print("hecho "+str(nMonth)+" "+str(nameList))
    except Exception as e:
        print("Exeption: {}".format(e))


nameFile = "dades.js"
generaMonthList(nameFile, "allList", 1)
#generaMonthList(nameFile, "februryList", 2)
#generaMonthList(nameFile, "marchList", 3)
#generaMonthList(nameFile, "aprilList", 4)
#generaMonthList(nameFile, "mayList", 5)
#generaMonthList(nameFile, "juneList", 6)
#generaMonthList(nameFile, "julyList", 7)
#generaMonthList(nameFile, "augustList", 8)
#generaMonthList(nameFile, "septemberList", 9)
#generaMonthList(nameFile, "octoberList", 10)
#generaMonthList(nameFile, "novemberList", 11)
#generaMonthList(nameFile, "decemberList", 12)
#

